stages:
  - build
  - test
  - deploy

junit:
  stage: test
  script:
    - ./gradlew test

release-artifacts:
  stage: deploy
  script:
    - ./gradlew build
  artifacts:
    paths:
      - ./build/libs/*.jar
      - ./build/resources/main/*.properties
