stages:
  - build
  - test
  - deploy
  - docker-build
  - docker-deploy

docker-build:
  stage: docker-build
  script:
    - docker-compose build

junit:
  stage: test
  script:
    - ./gradlew test

release-artifacts:
  stage: deploy
  script:
    - ./gradlew build
  artifacts:
    paths:
      - ./build/libs/*.jar
      - ./build/resources/main/*.properties

deploy-docker:
  stage: docker-deploy
  script:
    - docker-compose down --remove-orphans
    - docker-compose up -d
